# DB.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

def init_db(app):
    app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://root:@localhost/similarity_app"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    db.init_app(app)

# ---------------- USERS TABLE ----------------
class Users(db.Model):
    __tablename__ = 'users'

    user_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    role = db.Column(db.Enum('admin', 'lecturer', 'student'), nullable=False)
    is_verified = db.Column(db.Boolean, default=False)
    # verification_token = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def set_password(self, plain_password):
        self.password = generate_password_hash(plain_password)

    def check_password(self, plain_password):
        return check_password_hash(self.password, plain_password)

# ---------------- HISTORY TABLE ----------------
class AnalysisHistory(db.Model):
    __tablename__ = 'analysishistory'

    analysis_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.user_id'), nullable=False)
    modality = db.Column(db.Enum('document', 'image', 'code', 'text', 'url'), nullable=False)
    file_a_name = db.Column(db.Text, nullable=False)
    file_b_name = db.Column(db.Text, nullable=False)

    # path / filename as saved under uploads/ (string)
    save_path_a = db.Column(db.String(255))
    save_path_b = db.Column(db.String(255))

    # text previews (for showing in report)
    preview_a = db.Column(db.Text)
    preview_b = db.Column(db.Text)

    # diff HTML for document/code (generated by difflib.HtmlDiff)
    diff_html = db.Column(db.Text)
    
    text_a = db.Column(db.Text, nullable=True)   # new
    text_b = db.Column(db.Text, nullable=True)   # new
    similarity_score = db.Column(db.Float, nullable=False)
    report_url = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

# ---------------- CACHE TABLE ----------------
class FeatureCache(db.Model):
    __tablename__ = 'featurecache'

    cache_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    file_hash = db.Column(db.String(64), unique=True, nullable=False)
    embedding = db.Column(db.LargeBinary, nullable=False)
    modality = db.Column(db.Enum('document', 'image', 'code'), nullable=False)
    last_accessed = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
