"""init

Revision ID: 4988c617e289
Revises: 
Create Date: 2025-12-03 23:18:45.158212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4988c617e289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('save_path_a', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('save_path_b', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.drop_column('save_path_b')
        batch_op.drop_column('save_path_a')

    # ### end Alembic commands ###
