"""add text_a and text_b

Revision ID: eb112d263f21
Revises: ecfbb47d6f62
Create Date: 2025-12-11 23:40:49.808562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb112d263f21'
down_revision = 'ecfbb47d6f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_a', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('text_b', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.drop_column('text_b')
        batch_op.drop_column('text_a')

    # ### end Alembic commands ###
