"""add previews and diff columns

Revision ID: ecfbb47d6f62
Revises: 4988c617e289
Create Date: 2025-12-07 14:36:33.723377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfbb47d6f62'
down_revision = '4988c617e289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_a', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview_b', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('diff_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysishistory', schema=None) as batch_op:
        batch_op.drop_column('diff_html')
        batch_op.drop_column('preview_b')
        batch_op.drop_column('preview_a')

    # ### end Alembic commands ###
